// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAknWbKe2XpZIhwe4ImcqxVuuFq9PowVEw',
    appId: '1:864872876806:web:0d53fb2f9d28aa4821ac87',
    messagingSenderId: '864872876806',
    projectId: 'labs11-cf7df',
    authDomain: 'labs11-cf7df.firebaseapp.com',
    storageBucket: 'labs11-cf7df.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFyjo2KqqAoKLo-jwwm_Tasd4DjMrJXEY',
    appId: '1:864872876806:android:3edee669bfce6eff21ac87',
    messagingSenderId: '864872876806',
    projectId: 'labs11-cf7df',
    storageBucket: 'labs11-cf7df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5jSzCDOWz7LMBuhCgW-TgsiUYGY6lrWQ',
    appId: '1:864872876806:ios:4847febfaa721c4d21ac87',
    messagingSenderId: '864872876806',
    projectId: 'labs11-cf7df',
    storageBucket: 'labs11-cf7df.appspot.com',
    iosBundleId: 'com.example.labs11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5jSzCDOWz7LMBuhCgW-TgsiUYGY6lrWQ',
    appId: '1:864872876806:ios:dd6f930897dfa2c721ac87',
    messagingSenderId: '864872876806',
    projectId: 'labs11-cf7df',
    storageBucket: 'labs11-cf7df.appspot.com',
    iosBundleId: 'com.example.labs11.RunnerTests',
  );
}
